/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2019-09-03 12:52:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import com.hcl.ems.DaoConnection;
import java.sql.Connection;
import java.util.List;
import com.hcl.ems.LeaveHistory;
import com.hcl.ems.EmployeeBaL;
import com.hcl.ems.Employee;

public final class DashBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.hcl.ems.Employee");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.hcl.ems.DaoConnection");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("com.hcl.ems.LeaveHistory");
    _jspx_imports_classes.add("com.hcl.ems.EmployeeBaL");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head><style type=\"text/css\">\r\n");
      out.write("      .scrollable {\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        overflow-y: scroll;\r\n");
      out.write("        overflow-x: scroll;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"MyDetails\" style=\" position: absolute; top: 52px; left: 170px; border: 3px solid black; width: 600px; height: 134px; background-color: #D0D6F5;\">\r\n");

	String emp_id =(String) session.getAttribute("EMP_ID");
	Employee obj = EmployeeBaL.showEmployeeBal(Integer.parseInt(emp_id));

      out.write("\r\n");
      out.write("<table style='font-size: 13px; font-family: Verdana, Arial, Sans-Serif'><tr bgcolor=\"#D0D6F5\" ><th >\r\n");
      out.write("\tEmploy ID :</td><td style=\"width: 119px; height: 27px\">\r\n");
      out.write("\t");
      out.print(obj.getEmp_id() );
      out.write("</th><th >\r\n");
      out.write("\tMobile Number :</th><td >\t\r\n");
      out.write("\t");
      out.print(obj.getEmp_mob_no() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr bgcolor=\"#EDEFF9\" ><th style=\"width: 115px; \">\r\n");
      out.write("\tFull Name :</th><td style=\"height: 27px; width: 250px\">\r\n");
      out.write("\t");
      out.print(obj.getEmp_name() );
      out.write("</td><th style=\"width: 115px; \">\r\n");
      out.write("\tDate Joined :</th><td style=\"width: 105px; \">\r\n");
      out.write("\t");
      out.print(obj.getEmp_date_joined() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr bgcolor=\"#D0D6F5\"><th style=\"width: 131px; \">\r\n");
      out.write("\tEmail Address :</th><td style=\"width: 160px; height: 27px\">\r\n");
      out.write("\t");
      out.print(obj.getEmp_email() );
      out.write("</td><th>\r\n");
      out.write("\tDepartment :</th><td style=\"width: 89px; \">\r\n");
      out.write("\t");
      out.print(obj.getEmp_dpt_name() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr bgcolor=\"#EDEFF9\" ><td colspan=\"4\" style=\"width: 480px; height: 26px\"><center>\r\n");
      out.write("\tAvailable leave Balance :\r\n");
      out.write("\t<a style=\"color : red; font-size: 18px;\">");
      out.print(obj.getEmp_leave_balance() );
      out.write("</a></center></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"MyManager\" style=\"border: 3px solid black; position: absolute; top: 52px; left: 780px; width : 390px;height: 134px; background-color: #D0D6F5;\" >\r\n");
      out.write("\t");

	int emp_id1 = obj.getEmp_mgr_id();
	Employee obj1 = EmployeeBaL.showEmployeeBal(emp_id1);
	if (obj1.getEmp_name()==null) {
	
      out.write("<table  style=\"width: 380px;height:107px; font-size: 24px; font-family: Verdana, Arial, Sans-Serif\"><tr><td></td><td></td></tr><tr></tr><tr><td> <center>");
      out.print("No manager" );
      out.write("</td> </tr><tr></tr> </center></table>\r\n");
      out.write("\t");

	} else {
	
      out.write(" <table  style=\"width: 390px; font-size: 13px; font-family: Verdana, Arial, Sans-Serif\"><tr bgcolor=\"#EDEFF9\" style=\"height: 30px\"><th>\r\n");
      out.write("\tManager Id :</th><td>\r\n");
      out.write("\t");
      out.print(obj1.getEmp_id() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr bgcolor=\"#D0D6F5\" style=\"height: 30px\"><th>\r\n");
      out.write("\tFull Name :</th><td>\r\n");
      out.write("\t");
      out.print(obj1.getEmp_name() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr bgcolor=\"#EDEFF9\" style=\"height: 30px\"><th>\r\n");
      out.write("\tEmail Address :</th><td>\r\n");
      out.write("\t");
      out.print(obj1.getEmp_email() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr bgcolor=\"#D0D6F5\" style=\"height: 30px\"><th>\r\n");
      out.write("\tMobile Number :</th><td>\r\n");
      out.write("\t");
      out.print(obj1.getEmp_mob_no() );
      out.write("</td></tr>\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</div >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"scrollable\" id = \" myLeave\" style=\"border: 3px solid black; position:absolute; top: 195px; left: 172px; width : 997px; height : 170px;\" >\r\n");
      out.write("\t");

	List<LeaveHistory> lst = EmployeeBaL.leaveBal(Integer.parseInt(emp_id));
	
      out.write("<table  style=\"width: 997px; font-size: 12px; font-family: Verdana, Arial, Sans-Serif\"><tr bgcolor=\"#2873C4\" style=\"color :white;\"><td>Leave ID</td><td>Number of Days</td><td>Start Date</td><td>End Date</td><td>LeaveType</td>\r\n");
      out.write("\t\t<td>Status</td><td>Reason</td><td>Applied On</td><td>Manager Comments</td></tr>\t\r\n");
      out.write("\t<tr bgcolor=\"#D0D6F5\"><td colspan=\"9\"><center><a href=\"ApplyLeave.jsp\"><input type=\"button\" value=\"NEW Leave\" /></a></center></td></tr>\r\n");
      out.write("\t");

	if(lst != null){
		for(LeaveHistory leave : lst){
		
			
      out.write("<tr bgcolor=\"#D0D6F5\"><td>");
      out.print( leave.getLEA_ID());
      out.write("</td><td>");
      out.print( leave.getLEA_NO_OF_DAYS());
      out.write("</td><td>");
      out.print( leave.getLEA_START_DATE());
      out.write("</td><td>\r\n");
      out.write("\t\t\t");
      out.print( leave.getLEA_END_DATE());
      out.write("</td><td>");
      out.print( leave.getLEA_TYPE());
      out.write("</td><td>\r\n");
      out.write("\t\t\t");
if(leave.getLEA_STATUS().equals("APPROVED")){
      out.write("\r\n");
      out.write("\t\t\t<a style=\"color: green\" >");
      out.print( leave.getLEA_STATUS());
      out.write("</a>\r\n");
      out.write("\t\t\t");
 }else if(leave.getLEA_STATUS().equals("DENIED")){ 
      out.write("\r\n");
      out.write("\t\t\t<a style=\"color: Red\" >");
      out.print( leave.getLEA_STATUS());
      out.write("</a>\r\n");
      out.write("\t\t\t");
 } else{
      out.write("\r\n");
      out.write("\t\t\t ");
      out.print( leave.getLEA_STATUS());
      out.write(" \r\n");
      out.write("\t\t\t");
 }
      out.write("</td><td>");
      out.print(leave.getLEA_REASON() );
      out.write("</td><td>");
      out.print( leave.getLEA_APPLIED_ON());
      out.write("</td><td>");
      out.print( leave.getLEA_MGR_COMMENTS());
      out.write("</td></tr> ");

		}
	} else {
		
      out.write("<tr><td colspan=\"9\"><center> No Leave History Found</center></td></tr> ");

	}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("</div >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"scrollable\" id = \"EmpLeave\" style=\"border: 3px solid black; position:absolute; top: 375px; left: 170px; width : 998px; height : 210px;\">\r\n");
      out.write("\t");
  
	Connection con  = DaoConnection.getConnection();
	String cmd = "select EMP_ID from Employee where EMP_MGR_ID =?";
	PreparedStatement pst = con.prepareStatement(cmd);
	pst.setInt(1, Integer.parseInt(emp_id));
	ResultSet rs = pst.executeQuery();
	while(rs.next()){	
	Employee obj2 = EmployeeBaL.showEmployeeBal(rs.getInt("Emp_id"));
	List<LeaveHistory> lst1 = EmployeeBaL.leaveBal(rs.getInt("Emp_id"));
	

      out.write("\r\n");
      out.write("<form id=\"myform\" method=\"get\"><center style=\"font-size: 16px; font-family: Tahoma, Verdana, Arial, Sans-Serif\">\r\n");
      out.write("<table style='font-family: Verdana, Arial, Sans-Serif; font-size: 12px'>\r\n");
      out.write("\t<tr bgcolor=\"#2873C4\" style=\"color :white;\">\r\n");
      out.write("\t\t<th colspan=\"2\" style=\"width: 118px; \"><center>Employee Id</center></th>\r\n");
      out.write("\t\t<td style=\"width: 106px; \"><center>");
      out.print(obj2.getEmp_id() );
      out.write("</center></td>\r\n");
      out.write("\t\t<th colspan=\"2\" style=\"width: 208px; \"><center>Employee Name</center></th>\r\n");
      out.write("\t\t<td colspan=\"2\" style=\"width: 85px; height: 38px\"><center>");
      out.print(obj2.getEmp_name() );
      out.write("</center></td>\r\n");
      out.write("\t\t<th colspan=\"2\" style=\"width: 385px; \"><center style=\"width: 428px; \">Employee Leave Balance</center></th>\r\n");
      out.write("\t\t<td colspan=\"2\" style=\"width: 94px; \"><center>");
      out.print(obj2.getEmp_leave_balance() );
      out.write("</center></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr bgcolor=\"#D0D6F5\" style=\"height: 40px; \">\r\n");
      out.write("\t\t<th style=\"width: 40px; background-color: Gray\"></th>\r\n");
      out.write("\t\t<th style=\"width: 91px; \"><center>Leave Id</center></th>\r\n");
      out.write("\t\t<th style=\"width: 107px; \"><center>Number of days</center></th>\r\n");
      out.write("\t\t<th style=\"width: 96px; \"><center>Start Date</center> </th>\r\n");
      out.write("\t\t<th style=\"width: 92px; \"><center>End Date</center></th>\r\n");
      out.write("\t\t<th style=\"width: 91px; \"><center>Leave Type</center> </th>\r\n");
      out.write("\t\t<th style=\"width: 96px; height: 46px\"><center>Status </center></th>\r\n");
      out.write("\t\t<th style=\"width: 231px;\"><center style=\"width: 240px; \">Reason</center></th>\r\n");
      out.write("\t\t<th style=\"width: 161px; \">Comments</th>\r\n");
      out.write("\t\t<th style=\"width: 92px; \">Approve</th>\r\n");
      out.write("\t\t<th style=\"width: 90px; \">Deny</th>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");
 for(LeaveHistory i : lst1){
	      if(i.getLEA_STATUS().equals("PENDING")){
      out.write("\r\n");
      out.write("\t<tr bgcolor=\"#EDEFF9\" style=\"height: 40px; \">\r\n");
      out.write("\t\t<td style=\"width: 38px; background-color: Gray\"></td>\r\n");
      out.write("\t\t<td ><center><input type=\"hidden\" name=\"id\" value=");
      out.print(i.getLEA_ID() );
      out.write(' ');
      out.write('/');
      out.write('>');
      out.print(i.getLEA_ID() );
      out.write("</center></td>\r\n");
      out.write("\t\t<td ><center>");
      out.print(i.getLEA_NO_OF_DAYS() );
      out.write("</center></td>\r\n");
      out.write("\t\t<td ><center>");
      out.print(i.getLEA_START_DATE() );
      out.write("</center> </td>\r\n");
      out.write("\t\t<td><center>");
      out.print(i.getLEA_END_DATE() );
      out.write("</center></td>\r\n");
      out.write("\t\t<td ><center>");
      out.print(i.getLEA_TYPE());
      out.write("</center> </td>\r\n");
      out.write("\t\t<td style=\"width: 64px; \"><center>");
      out.print(i.getLEA_STATUS() );
      out.write("</center></td>\r\n");
      out.write("\t\t<td style=\"width: 197px;\" ><center style=\"width: 240px; \">");
      out.print(i.getLEA_REASON());
      out.write("</center></td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"comments\" /></td>\r\n");
      out.write("\t\t<td><center><input type=\"submit\" value=\"Approve\" form=\"myform\" formaction=\"approve.jsp\"/></center></td>\r\n");
      out.write("\t\t<td><center><input type=\"submit\"  value=\"Deny\" form=\"myform\" formaction=\"deny.jsp\"/></center></td>\r\n");
      out.write("\t\t</tr>");
} }
      out.write("\r\n");
      out.write("</table></br>\r\n");
      out.write("</center>\r\n");

	} 
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<center><a href=\"Login.jsp\" ><input type=\"button\" value=\"Logout\" /> </a></center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
